import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import {
  NATIVE_CRATES_DIR,
  NATIVE_NPM_DIR,
  NATIVE_TARGET_TRIPLES,
  nativeCrateDir,
  nativePackageDir,
} from "../index.ts";

/**
 * Discovery for the Rust workspace.
 *
 * Nothing is declared in a manifest: crates are whatever lives in
 * `packages/native/crates/*`, and each cdylib crate maps to the npm package of
 * the same name in `packages/native/npm/*`. Adding a crate is therefore just
 * adding a directory — no registry to keep in sync.
 */

export type NativeCrate = {
  /** Crate directory name. */
  name: string;
  /** Path relative to the repo root. */
  dir: string;
  /** `cdylib` — i.e. a napi binding with an npm package. */
  binding: boolean;
  /** Sibling crates this one depends on. */
  uses: string[];
};

export type NativeNpmPackage = {
  /** npm package directory name (== crate name). */
  name: string;
  /** Path relative to the repo root. */
  dir: string;
  /** Path to the crate that produces its binary. */
  crateDir: string;
  /** `napi.binaryName` — the .node file prefix. */
  binaryName: string;
  /** `napi.targets` — falls back to every supported triple. */
  targets: string[];
};

/**
 * Walks up from `start` until it finds the Rust workspace, so `mnative` works
 * from any package directory (turbo runs it with cwd = the package).
 */
export function findNativeRoot(start: string = process.cwd()): string {
  let dir = resolve(start);
  for (let depth = 0; depth < 32; depth++) {
    if (existsSync(join(dir, "packages", "native", "Cargo.toml"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return resolve(start);
}

function readDirs(path: string): string[] {
  if (!existsSync(path)) return [];
  return readdirSync(path, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

/** Every crate in the workspace, pure-Rust ones included. */
export function discoverCrates(root: string): NativeCrate[] {
  const cratesDir = join(root, "packages", "native", NATIVE_CRATES_DIR);
  const crates: NativeCrate[] = [];

  for (const name of readDirs(cratesDir)) {
    const manifest = join(cratesDir, name, "Cargo.toml");
    if (!existsSync(manifest)) continue;
    const content = readFileSync(manifest, "utf8");
    const uses = [...content.matchAll(/^\s*([\w-]+)\s*=\s*\{\s*path\s*=\s*"[^"]*"/gm)].map(
      (m) => m[1] ?? "",
    );
    crates.push({
      name,
      dir: nativeCrateDir(name),
      binding: /crate-type\s*=\s*\[[^\]]*cdylib/.test(content),
      uses: uses.filter(Boolean),
    });
  }

  return crates;
}

/** npm packages that own a napi binding (generated platform dirs are skipped). */
export function discoverPackages(root: string): NativeNpmPackage[] {
  const npmDir = join(root, "packages", "native", NATIVE_NPM_DIR);
  const packages: NativeNpmPackage[] = [];

  for (const name of readDirs(npmDir)) {
    const manifest = join(npmDir, name, "package.json");
    if (!existsSync(manifest)) continue;

    let pkg: { name?: string; napi?: { binaryName?: string; targets?: string[] } };
    try {
      pkg = JSON.parse(readFileSync(manifest, "utf8"));
    } catch {
      continue;
    }
    if (!pkg.napi) continue; // platform package generated by `napi create-npm-dirs`

    const crateDir = nativeCrateDir(name);
    if (!existsSync(join(root, crateDir, "Cargo.toml"))) continue;

    packages.push({
      name,
      dir: nativePackageDir(name),
      crateDir,
      binaryName: pkg.napi.binaryName ?? name,
      targets: pkg.napi.targets?.length ? pkg.napi.targets : [...NATIVE_TARGET_TRIPLES],
    });
  }

  return packages;
}

/**
 * Packages that can actually be built: a napi package whose crate declares
 * itself a `cdylib`.
 */
export function discoverBuildable(root: string): NativeNpmPackage[] {
  const bindingCrates = new Set(
    discoverCrates(root)
      .filter((crate) => crate.binding)
      .map((crate) => crate.name),
  );
  return discoverPackages(root).filter((pkg) => bindingCrates.has(pkg.name));
}
