pre-commit:
  parallel: true
  commands:
    biome:
      glob: "*.{ts,tsx,js,jsx,json,jsonc}"
      exclude: "configs/biome"
      run: bunx m lint:fix {staged_files}
      stage_fixed: true
    gitleaks:
      glob: "*"
      run: bunx m gitleaks protect --staged
    actionlint:
      glob: "{.github/workflows/*.yml,.github/workflows/*.yaml}"
      run: bun run ci:lint

commit-msg:
  commands:
    commitlint:
      run: bunx commitlint --config configs/commitlint/index.js --edit {1}
